-- Prisma migration: initial schema
-- !!! DO NOT EDIT THIS FILE MANUALLY if using Prisma Migrate later.
-- This file was generated for the test task.

-- Create enum-like tables first

CREATE TABLE "provider" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "name" TEXT NOT NULL UNIQUE
);

CREATE TABLE "message" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "providerId" TEXT NOT NULL,
  "sender" TEXT NOT NULL,
  "recipients" TEXT NOT NULL,
  "subject" TEXT,
  "sentAt" TIMESTAMPTZ NOT NULL,
  "inReplyTo" TEXT,
  "references" TEXT NOT NULL,
  "threadId" TEXT,
  "parentId" TEXT,
  CONSTRAINT "fk_message_provider" FOREIGN KEY ("providerId") REFERENCES "provider"("id"),
  CONSTRAINT "fk_message_thread" FOREIGN KEY ("threadId") REFERENCES "thread"("id"),
  CONSTRAINT "fk_message_parent" FOREIGN KEY ("parentId") REFERENCES "message"("id")
);

CREATE TABLE "message_reference" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "messageId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "externalId" TEXT NOT NULL,
  CONSTRAINT "fk_message_ref_message" FOREIGN KEY ("messageId") REFERENCES "message"("id"),
  CONSTRAINT "fk_message_ref_provider" FOREIGN KEY ("providerId") REFERENCES "provider"("id"),
  UNIQUE ("providerId", "externalId")
);

CREATE TABLE "thread" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "providerId" TEXT NOT NULL,
  "subject" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "thread_reference" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "threadId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "externalId" TEXT NOT NULL,
  CONSTRAINT "fk_thread_ref_thread" FOREIGN KEY ("threadId") REFERENCES "thread"("id"),
  CONSTRAINT "fk_thread_ref_provider" FOREIGN KEY ("providerId") REFERENCES "provider"("id"),
  UNIQUE ("providerId", "externalId")
);

CREATE TABLE "task" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "providerId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "data" TEXT,
  "status" TEXT NOT NULL,
  "error" TEXT,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT "fk_task_provider" FOREIGN KEY ("providerId") REFERENCES "provider"("id")
);

-- Migration lock file tracking